pipeline:
  build:
    image: python:3.4
    commands:
      - pip install -r dev-requirements.txt
      - flake8 setup.py drone tests
      - nosetests --with-coverage --cover-package drone -v

  matrix:
    PYTHON_VERSION:
      - 2.7
      - 3.4
      - 3.5
